# Values formatted like "_env:ENV_VAR_NAME:default_value" can be overridden
# by the specified environment variable. See
# https://github.com/yesodweb/yesod/wiki/Configuration#overriding-configuration-values-with-environment-variables

host:           "_env:HOST:*4" # any IPv4 host
# NB: The port `yesod devel` uses is distinct from this value. Set the
# `yesod devel` port from the command line.
port:           "_env:PORT:3000"
ip-from-header: "_env:IP_FROM_HEADER:false"

# Default behavior: determine the application root from the request headers.
# Uncomment to set an explicit approot
approot:        "_env:APPROOT:http://localhost:3000"

# Optional values with the following production defaults.
# In development, they default to the inverse.
#
# development: false
# detailed-logging: false
# should-log-all: false
# reload-templates: false
# mutable-static: false
# skip-combining: false

# NB: If you need a numeric value (e.g. 123) to parse as a String, wrap it
# in single quotes (e.g. "_env:PGPASS:'123'") See
# https://github.com/yesodweb/yesod/wiki/Configuration#parsing-numeric-values-as-strings

database:
  user:     "_env:PGUSER:"
  password: "_env:PGPASS:"
  host:     "_env:PGHOST:"
  port:     "_env:PGPORT:5432"
  # See config/test-settings.yml for an override during tests
  database: "_env:PGDATABASE:snowdrift_development"
  poolsize: "_env:PGPOOLSIZE:10"
