Default: &defaults
  user: snowdrift_development
  password: DGrhfkMc7W8vpMQazv8qlCyRjTdE2qE9
  host: localhost
  port: 5432
  database: snowdrift_development
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: snowdrift_test
  <<: *defaults

Staging:
  database: snowdrift_staging
  poolsize: 100
  <<: *defaults

Production:
  database: snowdrift_production
  poolsize: 100
  <<: *defaults
