Default: &defaults
  host: "127.0.0.1"
  port: 3000
  approot: "http://localhost:3000"
  copyright: "2013 Snowdrift.coop"
  source: "https://gitorious.org/snowdrift/snowdrift"
  githubrepo: "dlthomas/snowdrift"
  #analytics: UA-YOURCODE

Development:
  host: "*"
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "http://snowdrift.coop"
  port: 4003
  <<: *defaults
